

CREATE TABLE ESTABELECIMENTO(
    ID               SERIAL NOT NULL,
    NOME             VARCHAR(250) NOT NULL,
    NOME_FANTASIA    VARCHAR(250) NOT NULL,
    CNPJ             VARCHAR(250),
    EMAIL            VARCHAR(150) NOT NULL,
    TELEFONE         VARCHAR(14),
    LOGRADOURO       VARCHAR(60),
    NUMERO           VARCHAR(10),
    COMPLEMENTO      VARCHAR(60),
    BAIRRO           VARCHAR(60),
    CEP              VARCHAR(8),
    NOME_MUNICIPIO   VARCHAR(60),
    UF               CHAR(2),
    NOME_PAIS        VARCHAR(60),
    ID_TIPO_ESTABELECIMENTO INTEGER NOT NULL,

    PRIMARY KEY (ID),
    FOREIGN KEY (ID_TIPO_ESTABELECIMENTO) REFERENCES TIPO_ESTABELECIMENTO(ID)
);