drop table if exists VENDA;
drop table if exists ITENS_VENDA;

CREATE TABLE VENDA
(
    ID  SERIAL NOT NULL,
    DATA_VENDA TIMESTAMP,
    TIPO_PAGAMENTO VARCHAR(50) NOT NULL,
    VALOR_TOTAL  DECIMAL(18, 6),
    STATUS VARCHAR(50) NOT NULL,
    SITUACAO VARCHAR(50) NOT NULL,
    ID_CLIENTES INTEGER NOT NULL,

    PRIMARY KEY (ID),
    FOREIGN KEY (ID_CLIENTES) REFERENCES CLIENTES(ID)
);


CREATE TABLE ITENS_VENDA
(
     ID  SERIAL NOT NULL,
     QUANTIDADE INTEGER NOT NULL,
     ID_PRODUTO INTEGER NOT NULL,
     ID_VENDA INTEGER NOT NULL ,

    PRIMARY KEY (ID),
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID),
    FOREIGN KEY  (ID_VENDA) REFERENCES  VENDA(ID)

);